### ISSUE TITLE
Nie wiem co to za błąd :D

### ISSUE THREAD

**Issue by Qmpel** [Thefilippop1PL/Anti-Bot#2]
[12:22:42 WARN]: Exception in thread "pool-3-thread-16"
[12:22:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin Anti-Bot v1.
0 generated an exception while executing task 8
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljav
a/util/Collection;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335)
        at org.mcstats.Metrics.access$400(Metrics.java:57)
        at org.mcstats.Metrics$1.run(Metrics.java:223)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java
:53)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

**Comment by TheMolkaPL** [comment]
Zaktualizuj silnik (CraftBukkit/Spigot).
