### ISSUE TITLE
Błędy

### ISSUE THREAD

**Issue by kepo70** [Thefilippop1PL/Anti-Bot#9]
[15:32:17 ERROR]: Could not pass event AsyncPlayerChatEvent to Anti-Bot v1.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.chat(PlayerConnection.java:903) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:843) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:59) [mc.jar:git-Spigot-1387]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_72]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
at pl.filippop1.antibot.option.BlockCmdOption.onAsyncPlayerChatEvent(BlockCmdOption.java:43) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[mc.jar:git-Spigot-1387]
... 13 more
[15:32:17 ERROR]: Could not pass event AsyncPlayerChatEvent to Anti-Bot v1.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.chat(PlayerConnection.java:903) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:843) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:59) [mc.jar:git-Spigot-1387]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_72]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
at pl.filippop1.antibot.option.BlockCmdOption.onAsyncPlayerChatEvent(BlockCmdOption.java:43) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[mc.jar:git-Spigot-1387]
... 13 more
[15:32:17 INFO]: NerwuseK69 lost connection: §cPomyslnie zarejestrowany!
[15:32:18 INFO]: TheDolek1337 wywołał komendę: /spawn
[15:32:19 ERROR]: Could not pass event AsyncPlayerChatEvent to Anti-Bot v1.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.chat(PlayerConnection.java:903) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:843) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:59) [mc.jar:git-Spigot-1387]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_72]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
at pl.filippop1.antibot.option.BlockCmdOption.onAsyncPlayerChatEvent(BlockCmdOption.java:43) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[mc.jar:git-Spigot-1387]
... 13 more
[15:32:19 ERROR]: Could not pass event AsyncPlayerChatEvent to Anti-Bot v1.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-1387]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.chat(PlayerConnection.java:903) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:843) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [mc.jar:git-Spigot-1387]
at net.minecraft.server.v1_7_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:59) [mc.jar:git-Spigot-1387]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_72]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_72]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
at pl.filippop1.antibot.option.BlockCmdOption.onAsyncPlayerChatEvent(BlockCmdOption.java:43) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[mc.jar:git-Spigot-1387]
... 13 more

**Comment by TheMolkaPL** [comment]
Tak samo jak w #2, zaktualizuj silnik do minimum 1.7.10 ;)
